export enum HTTP_STATUS {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  DELETED = 204,
}
export enum RESPONSE_STATUS {
  SUCCESS = 'success',
  ERROR = 'error',
}
